branches:
  only:
    - blog

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - git config --global user.name "GaryNg-bot"
  - git config --global user.email "garyng.zhongbo@gmail.com"
  - git clone --branch gh-pages https://github.com/garyng/gtil.git dist
  - openssl aes-256-cbc -K $encrypted_07a3049e4f67_key -iv $encrypted_07a3049e4f67_iv -in ./travis/deploy_key.enc -out ~/.ssh/deploy_key -d
  - chmod 600 ~/.ssh/deploy_key
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/deploy_key

install:
  - npm install

script:
  - npm test
  - npm run build

after_script:
  - cd dist
  - cp index.html 404.html
  - git add --all .
  - git commit --message "chore(deploy): deploy from travis-ci"
  - git push --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

env:
  global:
    - GH_REF: github.com/garyng/gtil.git
